### ISSUE TITLE
Support for commands in windows

### ISSUE THREAD

**Issue by Krishna-teja** [geelen/git-smart#23]
I am having issues when I install it in windows. Both git smart-pull and git smart-merge are erroring out.

Git smart-merge:<pre><code>
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/safe_shell.rb:4:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/safe_shell.rb:4:in`execute'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_repo.rb:169:in `block in exec_git'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_repo.rb:168:in`chdir'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_repo.rb:168:in `exec_git'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_repo.rb:140:in`git'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_repo.rb:42:in `sha'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/commands/smart-merge.rb:14:in`block in <top (required)>'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_smart.rb:21:in `instance_exec'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_smart.rb:21:in`block in register'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_smart.rb:6:in `call'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/git_smart.rb:6:in`run'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/bin/git-smart-merge:7:in `<top (required)>'
        from c:/Ruby200-x64/bin/git-smart-merge:23:in`load'
        from c:/Ruby200-x64/bin/git-smart-merge:23:in `<main>'
</code></pre>

Git smart-pull:

<pre><code>
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-smart/safe_shel
l.rb:4:in `fork': fork() function is unimplemented on this machine (NotImplement
edError)
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/safe_shell.rb:4:in `execute'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_repo.rb:169:in `block in exec_git'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_repo.rb:168:in `chdir'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_repo.rb:168:in `exec_git'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_repo.rb:140:in `git'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_repo.rb:160:in `config'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_repo.rb:47:in `tracking_remote'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/comman
ds/smart-pull.rb:20:in `block in <top (required)>'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_smart.rb:21:in `instance_exec'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_smart.rb:21:in `block in register'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_smart.rb:6:in `call'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/lib/git-sm
art/git_smart.rb:6:in `run'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/git-smart-0.1.10/bin/git-sm
</code></pre>

**Comment by tellezhector** [comment]
+1

**Comment by BlueHatbRit** [comment]
+1 to this request, it would be really useful

**Comment by Xzq70r4** [comment]
+1

**Comment by bbartlett** [comment]
In order to get the "git-smart" commands to work under Windows, replace the `safe_smart.rb` file that comes with this gem (on my machine it is in `C:\Ruby22\lib\ruby\gems\2.2.0\gems\git-smart-0.1.10\lib\git-smart\` ) with the version from [https://github.com/envato/safe_shell/blob/master/lib/safe_shell.rb](https://github.com/envato/safe_shell/blob/master/lib/safe_shell.rb) .  Works fine after that.
