### ISSUE TITLE
smart-pull broken on Ruby 3.2.0 and later

### ISSUE THREAD

**Issue by kevwil** [geelen/git-smart#37]
```
/Users/keviwill/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/git-smart-0.1.11/lib/git-smart/git_repo.rb:23:in `git_dir': undefined method `exists?' for File:Class (NoMethodError)

    unless File.exists?(gitdir)
               ^^^^^^^^
Did you mean?  exist?
        from /Users/keviwill/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/git-smart-0.1.11/lib/git-smart/git_repo.rb:9:in `initialize'
        from /Users/keviwill/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/git-smart-0.1.11/lib/git-smart/git_smart.rb:21:in `new'
        from /Users/keviwill/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/git-smart-0.1.11/lib/git-smart/git_smart.rb:21:in `block in register'
        from /Users/keviwill/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/git-smart-0.1.11/lib/git-smart/git_smart.rb:6:in `run'
        from /Users/keviwill/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/git-smart-0.1.11/bin/git-smart-pull:7:in `<top (required)>'
        from /Users/keviwill/.rbenv/versions/3.2.1/bin/git-smart-pull:25:in `load'
        from /Users/keviwill/.rbenv/versions/3.2.1/bin/git-smart-pull:25:in `<main>'
```

**Comment by dep** [comment]
@kevwil 
Finally took matters into my own hands and forked a `git-smart-ruby-3` gem.  Just run this:
```
gem install git-smart-ruby-3
```
And say `y` at each prompt to overwrite the existings.
